#pragma once



#define START_TITLE_SCREEN ALLEGRO_GET_EVENT_TYPE('T','T','L','E')
#define START_INTRO_STORYBOARD_SCREEN ALLEGRO_GET_EVENT_TYPE('N','T','R','O')
#define START_CLOSING_STORYBOARD_SCREEN ALLEGRO_GET_EVENT_TYPE('O','T','R','O')
#define START_GAME_EVENT ALLEGRO_GET_EVENT_TYPE('S','T','R','T')
#define ENTER_DOOR_EVENT ALLEGRO_GET_EVENT_TYPE('D','O','O','R')
#define COLLECT_ITEM_EVENT ALLEGRO_GET_EVENT_TYPE('I','T','E','M')
#define USE_STONE_OF_DEFIANCE_EVENT ALLEGRO_GET_EVENT_TYPE('S','T','O','N')
#define QUIT_GAME_EVENT ALLEGRO_GET_EVENT_TYPE('Q','U','I','T')
#define PLAY_MUSIC_TRACK ALLEGRO_GET_EVENT_TYPE('M','U','S','C')
#define PLAY_SOUND_EFFECT ALLEGRO_GET_EVENT_TYPE('S','N','D','F')



