#pragma once



#define START_GAME_EVENT ALLEGRO_GET_EVENT_TYPE('S','T','R','T')
#define ENTER_DOOR_EVENT ALLEGRO_GET_EVENT_TYPE('D','O','O','R')
#define COLLECT_ITEM_EVENT ALLEGRO_GET_EVENT_TYPE('I','T','E','M')



